# <span style="color:darkblue"> QTM 151 - Quiz 2 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your name below

In [1]:
# Write your answer here
print("Annie He")

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [2]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

<font size = "5">

Import the libraries "numpy", "matplotlib.pyplot", and "pandas"

In [1]:
# Write your answer here

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<font size = "5">

Import the dataset "data_quiz/fifa23_players_basic.csv"

- It's a dataset on professional soccer players
- Rows correspond to players (18,539)
- Columns contain attributes of players (32)
- Try to view the dataset before starting

In [2]:
# Write your own code
soccerplayers = pd.read_csv("data_quiz/fifa23_players_basic.csv")

<font size = "5">

(a) Create a function and apply it to a column <br>

<font size = "3">

Step 1:
- Define a function with a parameter "country"
- If "country == United States", status = "US national"
- Otherwise, status = "Not a US national"
- The function returns "status"

Step 2:
- Extract the column "Nationality" in the dataset <br>
(be carefeful to write the "N" (capitalized)
- Create a new variable called "is_us_national" <br>
to assign each player to the correct age bracket

HINT: Use the ".apply()" function

In [6]:
# Write your own code
#step1
def fn_country(country):
    if (country == "United States"):
        status = "US national"
    else :
        status = "Not a US national"
    return(status)
#step2


soccerplayers["if they are US"] = soccerplayers["Nationality"].apply(fn_country)

<font size = "5">

(b) Use queries + global variables

<font size = "3">

- Compute the median of the column "Value(in Euro)" <br>
and store it as a variable
- Subset the players whose value is above the mean value <br>
  using ".query()"


HINT: Remember that there is a special syntax for <br>
when the column names have spaces (see Lecture 10) <br>
Reference the column as ``` `Wage(in Euro)`    ``` inside .query()

In [33]:
# Write your own code

value_median=soccerplayers["Value(in Euro)"].median()

subset_above_median = soccerplayers.query("`Value(in Euro)` > @value_median")

<font size = "5">

(c) Use sorting + ".iloc[]"

<font size = "3">

- Use ".sort_values()" to order the "Potental" column <br>
from highest to lowest
- Get a subset with the 15 players with the highest potential

In [25]:
# Write your own code
player_ascendingwage = soccerplayers.sort_values(by = "Potental",ascending = True)
display(player_ascendingwage.iloc[0:15,:])

KeyError: 'Potental'

<font size = "5">

(d) Create a function with five inputs $f(y,x,b0,b1,b2)$

<font size = "3">

$\qquad e = y - b_0 - b_1 * x - b_2 * x^2 $ <br>
$\qquad e2 = e^2$

- The function should return the mean of e2
- This is the mean-square error (mse)
- Call the function "fn_mse"
- Let $y$ be the column "Potential"
- Let $x$ be the column "Age" 
- Does <br>
$\qquad (b_0 = 90, b_1 = -1, b2 = -50)$ or <br>
$\qquad (b_0 = 90, b_1 = -1, b2 = 0)$ or <br>
$\qquad (b_0 = 90, b_1 = -1, b3 = 50)$ <br>
produce the lowest value of mse?

In [19]:
# Write your own code

def fn_mse(y, x, b0, b1, b2):
    e = np.mean((y - b0 - b1 * x)-b2*x**2)
    e2=e**2
    return e2


mse1 = fn_mse(soccerplayers["protential"], soccerplayers["Age"], 90, -1, -50)
mse2 = fn_mse(soccerplayers["Potential"], soccerplayers["Age"], 90, -1, 0)
mse3 = fn_mse(soccerplayers["Potential"], soccerplayers["Age"], 90, -1, 50)

print("MSE with b0 = 90 and b1 = -1 and b2= -50 : ", mse1)
print("MSE with b0 = 80 and b1 = -0.4 and b2= 0: ", mse2)
print("MSE with b0 = 80 and b1 = 1 and b3= 50: ", mse3)

KeyError: 'protential'

<font size = "5">

(e) Split a dataset into subsets

<font size = "3">

- Create ``` list_status = [0,1]```
- Create ``` list_prob = [0.5, 0.5]```
- Create a new variable $n$ with the number of rows of the dataset
- Use 
```python
    np.random.choice(list_status,
                     size = n,
                     p = list_prob)
```
$\qquad$ to create a new column called "status" <br>
$\qquad$ which randomly assigns each row to "0" with probability 50% <br>
$\qquad$ and to 1 with probability 50%
- Use .query() to subset all observations with status == 0.<br>
store it in a new dataset called "data0"
- Use .query() to subset all observations with status == 1.<br>
store it in a new dataset called "data1"

In [18]:
# Write your own code

list_status  = [0,1]
list_prob  = [0.5,0.5]
size_dataset = len(soccerplayers)

soccerplayers["status"] = np.random.choice(list_status, size = size_dataset, p = list_prob)

data_0 = soccerplayers.query('status == 0 ')
data_1 = soccerplayers.query('status == 1')

display(data_0.describe())
display(data_1.describe())

display(data_0)
display(data_1)

,Overall,Potential,Value(in Euro),Age,Height(in cm),Weight(in kg),TotalStats,BaseStats,Wage(in Euro),Release Clause,Joined On,Weak Foot Rating,Skill Moves,International Reputation,status
count,9233.000000,9233.000000,9.233000e+03,9233.000000,9233.000000,9233.000000,9233.000000,9233.000000,9233.000000,9.233000e+03,9233.000000,9233.000000,9233.000000,9233.000000,9233.0
mean,65.890718,71.073541,2.896023e+06,25.212174,181.511968,75.142532,1603.749269,358.125745,8963.327196,5.133004e+06,2020.364670,2.948446,2.365970,1.087079,0.0
std,6.794957,6.183214,7.547638e+06,4.702171,6.847947,7.001535,272.371774,39.766900,19707.557608,1.454103e+07,2.078902,0.680365,0.772299,0.358420,0.0
min,47.000000,49.000000,0.000000e+00,16.000000,155.000000,49.000000,759.000000,224.000000,0.000000,0.000000e+00,2002.000000,1.000000,1.000000,1.000000,0.0
25%,62.000000,67.000000,5.000000e+05,21.000000,177.000000,70.000000,1469.000000,330.000000,1000.000000,6.800000e+05,2020.000000,3.000000,2.000000,1.000000,0.0
50%,66.000000,71.000000,1.000000e+06,25.000000,182.000000,75.000000,1641.000000,359.000000,3000.000000,1.500000e+06,2021.000000,3.000000,2.000000,1.000000,0.0
75%,70.000000,75.000000,2.000000e+06,29.000000,186.000000,80.000000,1788.000000,385.000000,8000.000000,3.400000e+06,2022.000000,3.000000,3.000000,1.000000,0.0
max,91.000000,93.000000,1.165000e+08,44.000000,206.000000,105.000000,2312.000000,502.000000,450000.000000,2.610000e+08,2022.000000,5.000000,5.000000,5.000000,0.0

,Overall,Potential,Value(in Euro),Age,Height(in cm),Weight(in kg),TotalStats,BaseStats,Wage(in Euro),Release Clause,Joined On,Weak Foot Rating,Skill Moves,International Reputation,status
count,9306.000000,9306.000000,9.306000e+03,9306.000000,9306.000000,9306.000000,9306.000000,9306.000000,9306.000000,9.306000e+03,9306.000000,9306.000000,9306.000000,9306.000000,9306.0
mean,65.813669,70.960241,2.855061e+06,25.268429,181.589405,75.205029,1600.492693,357.768107,8686.836450,5.030774e+06,2020.370191,2.944444,2.366323,1.085536,1.0
std,6.781941,6.202245,7.721305e+06,4.734061,6.868302,7.025774,273.945268,39.491556,19212.372277,1.480147e+07,2.033880,0.667208,0.772597,0.359101,0.0
min,47.000000,48.000000,0.000000e+00,16.000000,156.000000,53.000000,779.000000,226.000000,0.000000,0.000000e+00,2003.000000,1.000000,1.000000,1.000000,1.0
25%,62.000000,67.000000,4.750000e+05,22.000000,177.000000,70.000000,1471.000000,331.000000,1000.000000,6.560000e+05,2020.000000,3.000000,2.000000,1.000000,1.0
50%,66.000000,71.000000,9.750000e+05,25.000000,182.000000,75.000000,1640.000000,358.000000,3000.000000,1.500000e+06,2021.000000,3.000000,2.000000,1.000000,1.0
75%,70.000000,75.000000,2.000000e+06,29.000000,186.000000,80.000000,1784.000000,384.000000,8000.000000,3.300000e+06,2022.000000,3.000000,3.000000,1.000000,1.0
max,91.000000,95.000000,1.905000e+08,42.000000,206.000000,104.000000,2283.000000,489.000000,420000.000000,3.667000e+08,2022.000000,5.000000,5.000000,5.000000,1.0

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,International Reputation,National Team Name,National Team Image Link,National Team Position,National Team Jersey Number,Attacking Work Rate,Defensive Work Rate,the_Nationality,if they are US,status
1,K. Benzema,Karim Benzema,91,91,64000000,"CF,ST",CF,Not a US national,https://cdn.sofifa.net/players/165/153/23_60.png,34,...,4,France,https://cdn.sofifa.net/flags/fr.png,ST,19,Medium,Medium,Not a US national,Not a US national,0
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Not a US national,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,4,Belgium,https://cdn.sofifa.net/flags/be.png,RF,7,High,High,Not a US national,Not a US national,0
7,M. Neuer,Manuel Neuer,90,90,13500000,GK,GK,Not a US national,https://cdn.sofifa.net/players/167/495/23_60.png,36,...,5,Germany,https://cdn.sofifa.net/flags/de.png,GK,1,Medium,Medium,Not a US national,Not a US national,0
11,Neymar Jr,Neymar da Silva Santos Jr.,89,89,99500000,LW,LW,Not a US national,https://cdn.sofifa.net/players/190/871/23_60.png,30,...,5,-,https://cdn.sofifa.net/flags/br.png,-,-,High,Medium,Not a US national,Not a US national,0
16,Ederson,Ederson Santana de Moraes,89,91,88000000,GK,GK,Not a US national,https://cdn.sofifa.net/players/210/257/23_60.png,28,...,3,-,https://cdn.sofifa.net/flags/br.png,-,-,Medium,Medium,Not a US national,Not a US national,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18525,J. Russell-Rowe,Jacen Russell-Rowe,48,65,120000,ST,CAM,Not a US national,https://cdn.sofifa.net/players/269/923/23_60.png,19,...,1,-,https://cdn.sofifa.net/flags/ca.png,-,-,Medium,Medium,Not a US national,Not a US national,0
18527,Liu Junxian,Junxian Liu,48,58,110000,ST,ST,Not a US national,https://cdn.sofifa.net/players/264/056/23_60.png,21,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,0
18528,Zhang Yue,Yue Zhang,48,56,110000,RM,LM,Not a US national,https://cdn.sofifa.net/players/268/922/23_60.png,22,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,0
18532,H. Singh,Harmanpreet Singh,48,56,100000,ST,ST,Not a US national,https://cdn.sofifa.net/players/259/745/23_60.png,20,...,1,-,-,-,-,Medium,Low,Not a US national,Not a US national,0
18536,L. Mullan,Liam Mullan,47,67,130000,CM,RM,Not a US national,https://cdn.sofifa.net/players/267/823/23_60.png,18,...,1,-,-,-,-,High,Medium,Not a US national,Not a US national,0

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,International Reputation,National Team Name,National Team Image Link,National Team Position,National Team Jersey Number,Attacking Work Rate,Defensive Work Rate,the_Nationality,if they are US,status
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Not a US national,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,5,Argentina,https://cdn.sofifa.net/flags/ar.png,RW,10,Low,Low,Not a US national,Not a US national,1
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Not a US national,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,5,Poland,https://cdn.sofifa.net/flags/pl.png,ST,9,High,Medium,Not a US national,Not a US national,1
4,K. Mbappé,Kylian Mbappé,91,95,190500000,"ST,LW",ST,Not a US national,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,4,France,https://cdn.sofifa.net/flags/fr.png,ST,10,High,Low,Not a US national,Not a US national,1
5,M. Salah,Mohamed Salah,90,90,115500000,RW,RW,Not a US national,https://cdn.sofifa.net/players/209/331/23_60.png,30,...,4,-,-,-,-,High,Medium,Not a US national,Not a US national,1
6,T. Courtois,Thibaut Courtois,90,91,90000000,GK,GK,Not a US national,https://cdn.sofifa.net/players/192/119/23_60.png,30,...,4,Belgium,https://cdn.sofifa.net/flags/be.png,GK,1,Medium,Medium,Not a US national,Not a US national,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18533,Pi Ziyang,Ziyang Pi,47,60,110000,CM,CAM,Not a US national,https://cdn.sofifa.net/players/269/066/23_60.png,19,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,1
18534,D. Collins,Darren Collins,47,56,110000,"ST,RM",CAM,Not a US national,https://cdn.sofifa.net/players/243/725/23_60.png,21,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,1
18535,Yang Dejiang,Dejiang Yang,47,57,90000,CDM,CDM,Not a US national,https://cdn.sofifa.net/players/261/933/23_60.png,17,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,1
18537,D. McCallion,Daithí McCallion,47,61,100000,CB,CB,Not a US national,https://cdn.sofifa.net/players/267/824/23_60.png,17,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,1
18538,N. Rabha,Nabin Rabha,47,50,60000,LB,LB,Not a US national,https://cdn.sofifa.net/players/261/424/23_60.png,25,...,1,-,-,-,-,Medium,Medium,Not a US national,Not a US national,1

<font size = "5">

(f) Create two overlapping histogram plots

<font size = "3">

- This function requires the two datasets you created in (e)
- Display the distribution of "Overall" for "data0" and "data1"
- Use the "alpha" option to make the graphs semitransparent
- You will need to add a legend, label the axes, and the title

Note: The goal of this question is to illustrate that random <br>
assignment produces very similar distributions between two groups

In [20]:
# Write your own code
list_unique_status = pd.unique(soccerplayers["status"])

for unique_status in list_unique_status:
    temporarydataframe = soccerplayers.query("status == @unique_status")
    plt.hist(temporarydataframe[" "], alpha=0.5)

plt.legend(labels=list_unique_status, title="Status")

plt.xlabel("")
plt.ylabel("frequency")
plt.title("the overall graph")

KeyError: ''